#!/usr/bin/env bash

set -x

docker volume ls
docker prune -f

docker-compose build
docker-compose up -d
docker exec -ti opensnporgdocker_rails_1 bash -l -c 'bundle exec rake db:reset'

i=10
while
  curl -sf "http://localhost:8080/" > /dev/null
  status=$?
  [ $status -ne 0 -a $i -gt 0 ]
do
  sleep 1
  i=$((i-1))
done

docker-compose rm -sfv
exit $status
